core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nadwislanin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

nadwislanin/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('reserve/', views.reserve, name='reserve'),
    path('reserve/<int:tour>/', views.reserve, name='reserve'),
    path('tours/', views.tours, name='tours'),
    path('guest_page/', views.guest_page, name='guest_page'),
    path('send_email/<str:pk>/<int:nr>/', views.send_email, name='send_email'),
    path('list/', views.list_all, name='list'),
    path('list/<str:opt>/', views.list_all, name='list'),
    path('update/<str:pk>/', views.update, name='update'),
    path('delete/<str:pk>/', views.delete, name='delete'),
    path('info/', views.info, name='info'),
    path('rules/', views.rules, name='rules'),
    path('rodo/', views.rodo, name='rodo'),
    path('gallery/', views.gallery, name='gallery')
    ]

nadwislanin/models.py
from django.db import models
from django.contrib.auth.models import User


tour_choices = [('1', 'Mochty-smok tajemnice i legendy'),
                ('2', 'Ruiny spichlerza widziane z Narwi'),
                ('3', 'Kierunek Leoncin na styku trzech kultur')]


text_one = 'Dziękujemy za zainteresowanie rezerwacją rejsu Nadwiślaninem. \n' \
        'Potwierdzamy możliwość jego zorganizowania w dniu ... o godzinie ... . \n' \
        'Prosimy o dokonanie wpłaty na podany numer konta: 63 8011 0008 0040 0409 6821 0001. \n' \
        'Jesteśmy do dyspozycji w przypadku dodatkowych pytań. \nPozdrawiamy serdecznie, \nzałoga Nadwiślanina'

text_two = 'Dziękujemy za dokonanie wpłaty za rejs Nadwiślaninem. \nPotwierdzamy rezerwację w terminie ... . \n' \
         'Prosimy o przybycie 15 minut przed potwierdzoną godziną rejsu. \n' \
         'W systemie rezerwacyjnym po zalogowaniu istnieje możliwość sprawdzenia jego szczegółów. \n' \
         'Do zobaczenia w „Modlin Plaża”! \nPozdrawiamy, \nzałoga Nadwiślanina'


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Nazwa użytkownika")
    email = models.EmailField(verbose_name="Adres e-mail")
    datetime = models.DateTimeField(verbose_name="Preferowana data i godzina rejsu")
    tour = models.CharField(max_length=2, choices=tour_choices, verbose_name="Wybrana wycieczka")
    feedback = models.TextField(verbose_name="Informacje dodatkowe", blank=True)
    new = models.BooleanField(default=True, verbose_name="Nowe zapytanie")
    confirmation = models.BooleanField(default=False, verbose_name="Potwierdzenie")
    email_text_one = models.TextField(default=text_one, verbose_name="Wiadomość e-mail I")
    email_text_two = models.TextField(default=text_two, verbose_name="Wiadomość e-mail II")

    def __str__(self):
        return f"""Rezerwacja ID {self.id}: {self.user} -> {self.datetime}"""

nadwislanin/forms.py
from django import forms
from .models import Reservation


class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        exclude = ['user', 'new', 'confirmation', 'email_text_one', 'email_text_two']
        widgets = {
            'datetime': DateTimeInput(),
        }


class DetailsForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

nadwislanin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
from datetime import datetime

from .forms import ReservationForm, DetailsForm
from .models import Reservation


def index(request):
    return render(request, 'nadwislanin/index.html')


@login_required
def reserve(request, tour=0):
    tour_number = tour
    form = ReservationForm(request.POST or None, initial={'tour': tour_number})

    if form.is_valid():
        res_email = form.cleaned_data['email']
        res_datetime = form.cleaned_data['datetime']
        res_tour = form.cleaned_data['tour']
        res_feedback = form.cleaned_data['feedback']

        res = Reservation(user=request.user, email=res_email, datetime=res_datetime, tour=res_tour,
                          feedback=res_feedback)
        res.save()

        context = {'name': request.user, 'datetime': res_datetime, 'email': res_email}
        return render(request, 'nadwislanin/thankyou.html', context)

    context = {'form': form}
    return render(request, 'nadwislanin/reservation.html', context)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('login')
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)


@login_required
def guest_page(request):
    reservations = Reservation.objects.filter(user=request.user)
    context = {'reservations': reservations}
    return render(request, 'nadwislanin/guest_page.html', context)


@login_required
def send_email(request, pk, nr):
    res = Reservation.objects.get(id=pk)

    if nr == 1:
        send_mail('Zapytanie - rejs Nadwiślaninem', res.email_text_one,
                  'biuro@enjoyleoncin.pl', [res.email], fail_silently=False)
        res.new = False

    elif nr == 2:
        send_mail('Potwierdzenie rejsu Nadwiślaninem', res.email_text_two,
                  'biuro@enjoyleoncin.pl', [res.email], fail_silently=False)
        res.confirmation = True

    res.save()
    messages.warning(request, 'Wiadomość została wysłana!')
    return redirect('update', res.id)


@login_required
def list_all(request, opt=all):
    option = opt

    if request.user.is_superuser:
        reservations = Reservation.objects.filter(datetime__gte=datetime.now())
        if option == 'new':
            reservations = Reservation.objects.filter(datetime__gte=datetime.now(), new=True, confirmation=False)
        elif option == 'old':
            reservations = Reservation.objects.filter(datetime__gte=datetime.now(), new=False, confirmation=False)
        elif option == 'cf':
            reservations = Reservation.objects.filter(datetime__gte=datetime.now(), new=False, confirmation=True)
        elif option == 'past':
            reservations = Reservation.objects.filter(datetime__lt=datetime.now())

        context = {'reservations': reservations}
        return render(request, 'nadwislanin/list_all.html', context)

    else:
        return HttpResponse('<h3>Nie masz uprawnień, aby wejść na tę stronę!</h3>')


@login_required
def update(request, pk):
    res = Reservation.objects.get(id=pk)
    form = DetailsForm(instance=res)

    if request.method == 'POST':
        form = DetailsForm(request.POST, instance=res)

        if form.is_valid():
            form.save()

            return redirect('update', res.id)

    context = {'form': form, 'res': res}
    return render(request, 'nadwislanin/details.html', context)


@login_required
def delete(request, pk):
    res = Reservation.objects.get(id=pk)
    res.delete()
    return redirect('list')


def tours(request):
    return render(request, 'nadwislanin/tours.html')


def info(request):
    return render(request, 'nadwislanin/info.html')


def rules(request):
    return render(request, 'nadwislanin/rules.html')


def rodo(request):
    return render(request, 'nadwislanin/rodo.html')


def gallery(request):
    return render(request, 'nadwislanin/gallery.html')

nadwislanin/templates/nadwislanin/base.html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>Nadwiślanin</title>
  </head>
  <body>

  {% load static %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 fw-bold">
                <li class="nav-item">
                    <a href="https://enjoyleoncin.pl/"><img src="{% static 'nadwislanin/enjoy_logo.jpg' %}" width="45" height="45"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tours' %}">Wycieczki</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'reserve' %}">Rezerwacja</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'info' %}">Rezerwacja</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gallery' %}">Galeria</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rules' %}">Regulamin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rodo' %}">RODO</a>
                </li>

            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Logowanie</a>
                </li>
            </ul>

            {% else %}
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle fw-bold" role="button" data-bs-toggle="dropdown" aria-expanded="false">Witaj {{ user|title }}!</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'guest_page' %}">Moje zapytania</a></li>
                        {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'list' %}">Lista zapytań</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Wyloguj</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Wyloguj</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            {% endif %}

        </div>
    </nav>

    <div class="container mt-4">


      {% block content %}

      {% endblock %}

    </div>
  </body>
</html>

nadwislanin/templates/nadwislanin/details.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}


    <div class="row">
        <div class="col-md-4">
            <a class="btn btn-warning mb-3" href="{% url 'list' %}">Powrót do listy</a>
        </div>
        <div class="col-md-3">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible py-2 text-end" role="alert">
                <span class="fst-italic">{{ message }}</span>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-7">

            <div class="card">
                <form action="" method="POST">
                    {% csrf_token %}
                <div class="card-header fw-bold">
                    Szczegóły zapytania (ID: {{ res.id }})
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="mb-4">
                                {{ form.user|as_crispy_field }}
                            </div>
                            <div class="mb-4">
                                {{ form.email|as_crispy_field }}
                            </div>
                            <div class="mb-4">
                                {{ form.datetime|as_crispy_field }}
                            </div>
                            <div class="mb-4">
                                {{ form.tour|as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="mb-4">
                                {{ form.feedback|as_crispy_field }}
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    {{ form.new|as_crispy_field }}
                                </div>
                                <div class="col-sm-6">
                                    {{ form.confirmation|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            {{ form.email_text_one|as_crispy_field }}
                            <a class="btn btn-warning mt-2" href="{% url 'send_email' pk=res.id nr=1 %}">Wyślij maila</a>
                        </div>
                        <div class="col-sm-6">
                            {{ form.email_text_two|as_crispy_field }}
                            <a class="btn btn-warning mt-2" href="{% url 'send_email' pk=res.id nr=2 %}">Wyślij maila</a>
                        </div>
                    </div>
                </div>

                <div class="card-footer text-end">
                    <button type="submit" class="btn btn-warning">Zapisz zmiany</button>
                </div>
                </form>
            </div>

        </div>

        <div class="col-md-5 text-end">
            <img src="{% static 'nadwislanin/logo.jpg' %}" width="400" height="400">
        </div>

    </div>



{% endblock %}

nadwislanin/templates/nadwislanin/gallery.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}


  <div id="carouselIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="6" aria-label="Slide 7"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="7" aria-label="Slide 8"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="8" aria-label="Slide 9"></button>
          <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="9" aria-label="Slide 10"></button>
      </div>
      <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'nadwislanin/gallery_1.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_2.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_3.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_4.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_5.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_6.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/front.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/nadwiślanin.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/modlin.jpg' %}" class="d-block w-100">
          </div>
          <div class="carousel-item">
              <img src="{% static 'nadwislanin/gallery_7.jpg' %}" class="d-block w-100">
          </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
      </button>
  </div>
  <div class="row mt-2">
      <p class="text-end fw-bold fst-italic">Zdjęcia: Paulina Gocałek</p>
  </div>



{% endblock %}

nadwislanin/templates/nadwislanin/guest_page.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}


        <h5>Moje zapytania:</h5>
		
        <div class="row mt-4">
            <div class="col-md-5">
                {% for res in reservations %}
                <div class="card border-warning mb-3">
                    <div class="card-header py-1">ID: {{res.id}}</div>
                    <div class="card-body">
                        <ul class="card-text">
                            <li>Data: {{res.datetime|date }}</li>
                            <li>Godzina: {{res.datetime|time}}</li>
                            <li>Wycieczka: {{res.get_tour_display }} </li>
                        </ul>
                    </div>
                    <div class="card-footer py-0 text-end">
                        {% if res.confirmation %}
                        <p>Status: <strong>rezerwacja</strong></p>
                        {% else %}
                        <p>Status: <strong>zapytanie</strong></p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="col-md-6 text-end">
                <img src="{% static 'nadwislanin/front.jpg' %}" width="504" height="378">
            </div>
        </div>



{% endblock %}

nadwislanin/templates/nadwislanin/index.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}


    <div class="mb-4" align="center">
        <h2>Rejsy edukacyjno-widokowe drewnianą łodzią tradycyjną</h2>
    </div>

    <div class="row mb-4">
        <div class="col-md-5">
            <img src="{% static 'nadwislanin/nadwiślanin.jpg' %}" width="504" height="378">
        </div>
        <div class="col-md-7 fst-italic">
            <h5><p>ENJOY LEONCIN - Organizacja działa od 2017 roku głównie na terenie gminy Leoncin. Naszym celem jest promocja regionu oraz praca społeczna
                na rzecz mieszkańców. W latach ubiegłych udało się nam wybudować drewnianą łódź, która służy do promocji Stowarzyszenia i regionu.</p>
                <p>Zorganizowaliśmy 3 edycje Wiślanych Spotkań – rodzaj pikniku dla mieszkańców i gości, odbyły się seanse w Kinie Leo, z naszej
                    inicjatywy zawiązała się grupa nordic walking, która regularnie spaceruje po Kampinoskim Parku Narodowym.</p>
                <p>W 2021 roku uczestniczyliśmy w akcji Sprzątamy Puszczę Kampinoską oraz byliśmy organizatorami wielkiego sprzątania gminy Leoncin.</p>
                <p>Naszą łodzią pływamy po Wiśle i Narwi, są to rejsy na zmówienie bądź udział w imprezach tematycznych nad rzekami. Nasze plany wiążą
                    się z wykorzystaniem łodzi w celach edukacyjnych – bezpieczeństwo na rzece, ekologia (sprzątanie rzeki z łodzi) oraz historia widziana z rzeki.</p></h5>
        </div>
    </div>

    <div class="row mb-4">
        <h2 class="text-end">Motto: Płyń z nami, opowiemy Ci historię widzianą z rzeki!</h2>
    </div>
    <div class="row">
        <img src="{% static 'nadwislanin/mazowsze_logo.jpg' %}">
    </div>
    <div class="row fw-bold fst-italic">
         <p>„Projekt dofinansowany ze środków Programu Fundusz Inicjatyw Obywatelskich oraz środków Samorządu Województwa
             Mazowieckiego w ramach programu „Mazowsze Lokalnie” realizowanego przez Stowarzyszenie Europa i My,
             Stowarzyszenie BORIS, Stowarzyszenie SOKIAL oraz Fundację Fundusz Współpracy.”</p>
    </div>



{% endblock %}

nadwislanin/templates/nadwislanin/info.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}


    <div class="row">

        <div class="col-md-6">
            <a class="btn btn-warning mt-2 mb-4" href="{% url 'login' %}">Zaloguj się, aby dokonać rezerwacji!</a>
            <img src="{% static 'nadwislanin/gallery_2.jpg' %}" width="504" height="378">
        </div>
        <div class="col-md-6">
            <div class="card mt-2">
                <div class="card-header fw-bold">Informacje praktyczne</div>
                <div class="card-body">
                    <div class="row">
                        <p>Czas trwania rejsu w zależności od warunków na rzece - od 1,5 do 2 godzin.</p>
                        <p>Pływamy od kwietnia do października:<br>- w tygodniu od 15.00 do zmroku,<br>- w weekendy od 10.00 do zmroku.</p>
                        <p>Liczba osób na pokładzie - 12 ze sternikiem.</p>
                        <p>Wsiadamy w miejscu „Modlin Plaża” -<br>ul. Mieszka I 6A, Nowy Dwór Mazowiecki<br>
                            Podczas parkowania i korzystania z infrastruktury „Modlin Plaża”<br>obowiązuje regulamin właściciela miejsca.</p>
                        <p>Cena wynajmu łodzi za rejs ze sternikiem - 500 zł.</p>
                        <p>Płatność na konto:<br>Stowarzyszenie Enjoy Leoncin<br>pl. R. Kobendzy 3, 05-155 Leoncin<br>
                            Numer konta: 63 8011 0008 0040 0409 6821 0001</p>
                    </div>
                </div>
                <div class="card-footer">
                    <a class="btn btn-warning" href="{% url 'rules' %}">Regulamin rejsów</a>
                    <a class="btn btn-warning" href="{% url 'rodo' %}">RODO</a>
                </div>
            </div>
        </div>

    </div>


{% endblock %}

nadwislanin/templates/nadwislanin/list_all.html
{% extends "nadwislanin/base.html" %}
{% block content %}


    <h5>Lista wszystkich zapytań:</h5>

        <div class="row mb-4 mt-4">
            <div class="col-md-6">
                <a class="btn btn-warning" href="{% url 'list' opt='new' %}">Nowe</a>
                <a class="btn btn-warning" href="{% url 'list' opt='old' %}">Niepotwierdzone</a>
                <a class="btn btn-warning" href="{% url 'list' opt='cf' %}">Potwierdzone</a>
                <a class="btn btn-warning" href="{% url 'list' opt='past' %}">Wcześniejsze rezerwacje</a>
            </div>
        </div>


        {% for res in reservations %}

        <div class="row">
            <div class="col-md-5">

                <div class="card border-warning mb-3">
                    <div class="card-header py-1"><span class="fw-bold">{{ res.user }}</span> -> ID: {{res.id}}</div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <ul class="card-text">
                                    <li>Data: {{res.datetime|date }}</li>
                                    <li>Godzina: {{res.datetime|time}}</li>
                                </ul>
                            </div>
                            <div class="col-md-4">
                                <a class="btn btn-outline-warning btn-sm" href="{% url 'update' res.id %}">Szczegóły</a>
                                <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#cxModal">Usuń</button>
                            </div>
                            <div class="modal fade" id="cxModal" tabindex="-1" aria-labelledby="cxModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body fw-bold">
                                            Czy na pewno chcesz usunąć to zapytanie?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Nie</button>
                                            <a class="btn btn-danger btn-sm" href="{% url 'delete' res.id %}">Tak</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        {% endfor %}



{% endblock %}

nadwislanin/templates/nadwislanin/rodo.html
{% extends "nadwislanin/base.html" %}
{% block content %}

{% load static %}

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header fw-bold">RODO</div>
                <div class="card-body">
                    <p class="mb-3">Zgodnie z art. 13 ust. 1 i 2 ogólnego rozporządzenia o ochronie danych osobowych z dnia 27 kwietnia 2016 r.
                    w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu
                    takich danych oraz uchylenia dyrektywy 95/46/WE (Dz. Urz. UE. L. Nr 119, str. 1) zwanym dalej „RODO” informuję, iż:</p>
                    <ol>
                        <li>Administratorem Pani/Pana danych osobowych jest Stowarzyszenie Enjoy Leoncin z siedzibą w Leoncinie, pl. R. Kobendzy 3, 05-155 Leoncin, email: biuro@enjoyleoncin.pl.</li>
                        <li>Pani/Pana dane osobowe przetwarzane będą w celach związanych z działalnością statutową, udziałem w programach oraz wydarzeniach organizowanych przez Stowarzyszenie Enjoy Leoncin.</li>
                        <li>Pani/Pana dane przetwarzane będą wyłącznie na podstawie wcześniej udzielonej zgody w zakresie i celu określonym w treści zgody (art. 6 ust. 1 lit. a RODO).</li>
                        <li>Odbiorcami Pani/Pana danych osobowych będą podmioty uprawnione do uzyskania danych osobowych na podstawie przepisów prawa oraz podmioty, którym Administrator
                            powierzył przetwarzanie danych osobowych na podstawie umów powierzenia przetwarzania danych osobowych.</li>
                        <li>Pani/Pana dane przechowywane będą przez okres niezbędny do realizacji celu, dla jakiego zostały zebrane w okresie trwałości umowy i konieczności zachowania
                            dokumentacji projektu do celów kontrolnych lub do czasu wniesienia sprzeciwu wobec przetwarzania, o ile nie występują prawnie uzasadnione podstawy dalszego
                            przetwarzania danych. Po upływie 5 lat dane podlegać będą brakowaniu.</li>
                        <li>Posiada Pani/Pan prawo dostępu do treści swoich danych oraz prawo ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo do przenoszenia danych
                            osobowych, prawo wniesienia sprzeciwu, oraz prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania.</li>
                        <li>Przysługuje Pani/Panu prawo wniesienia skargi do organu nadzorczego właściwego w sprawach ochrony danych osobowych.</li>
                        <li>Podanie danych jest dobrowolne i niezbędne do realizacji ww. projektu, w przypadku niepodania danych niemożliwe jest zawarcie umowy.</li>
                        <li>Państwa dane osobowe nie podlegają zautomatyzowanemu podejmowaniu decyzji, w tym profilowaniu oraz, co do zasady, nie będą przekazywane do państw trzecich.</li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-end">
            <img src="{% static 'nadwislanin/logo_bw.jpg' %}" width="390.5" height="397">
        </div>
    </div>



{% endblock %}